python_blog/python_blog/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from blog.views import  index
from django.conf import settings
from blog.upload import upload_image

urlpatterns = [
    url(r"^uploads/(?P<path>.*)$", \
                "django.views.static.serve", \
                {"document_root": settings.MEDIA_ROOT,}),
    url(r'^admin/upload/(?P<dir_name>[^/]+)$', upload_image, name='upload_image'),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^$',index,  name='index'),

]

python_blog/blog/models.py
#coding:utf-8
from django.db import models
from django.contrib.auth.models import AbstractUser
# Create your models here.

# 用户模型.
# 第一种：采用的继承方式扩展用户信息（本系统采用）
# 扩展：关联的方式去扩展用户信息
class User(AbstractUser):
    avatar = models.ImageField(upload_to='avatar/%Y/%m', default='avatar/default.png', max_length=200, blank=True, null=True, verbose_name='用户头像')
    qq = models.CharField(max_length=20, blank=True, null=True, verbose_name='QQ号码')
    mobile = models.CharField(max_length=11, blank=True, null=True, unique=True, verbose_name='手机号码')
    url = models.URLField(max_length=100, blank=True, null=True, verbose_name='个人网页地址')

    class Meta:
        verbose_name = '用户'
        verbose_name_plural = verbose_name
        ordering = ['-id']

    def __unicode__(self):
        return self.username

#tag (标签)
class Tag(models.Model):
    name = models.CharField(max_length=30,verbose_name='标签名称')

    class Meta:
        verbose_name = '标签'
        verbose_name_plural = verbose_name

    def __unicode__(self):
        return self.name

#分类
class Category(models.Model):
    name = models.CharField(max_length=30, verbose_name='分类名称')
    index = models.IntegerField(verbose_name='分类的排序')

    class Meta:
        verbose_name = '分类'
        verbose_name_plural = verbose_name

    def __unicode__(self):
        return self.name

# 文章模型
class Article(models.Model):
    title = models.CharField(max_length=50, verbose_name='文章标题')
    desc = models.CharField(max_length=50, verbose_name='文章描述')
    content = models.TextField(verbose_name='文章内容')
    click_count = models.IntegerField(default=0, verbose_name='点击次数')
    is_recommend = models.BooleanField(default=False, verbose_name='是否推荐')
    date_publish = models.DateTimeField(auto_now_add=True, verbose_name='发布时间')
    user = models.ForeignKey(User, verbose_name='用户')
    category = models.ForeignKey(Category, blank=True, null=True, verbose_name='分类')
    tag = models.ManyToManyField(Tag, verbose_name='标签')

    #objects = ArticleManager()

    class Meta:
        verbose_name = '文章'
        verbose_name_plural = verbose_name
        ordering = ['-date_publish']

    def __unicode__(self):
        return self.title

# 评论模型
class Comment(models.Model):
    content = models.TextField(verbose_name='评论内容')
    username = models.CharField(max_length=30, blank=True, null=True, verbose_name='用户名')
    email = models.EmailField(max_length=50, blank=True, null=True, verbose_name='邮箱地址')
    url = models.URLField(max_length=100, blank=True, null=True, verbose_name='个人网页地址')
    date_publish = models.DateTimeField(auto_now_add=True, verbose_name='发布时间')
    user = models.ForeignKey(User, blank=True, null=True, verbose_name='用户')
    article = models.ForeignKey(Article, blank=True, null=True, verbose_name='文章')
    pid = models.ForeignKey('self', blank=True, null=True, verbose_name='父级评论')

    class Meta:
        verbose_name = '评论'
        verbose_name_plural = verbose_name

    def __unicode__(self):
        return str(self.id)

# 友情链接
class Links(models.Model):
    title = models.CharField(max_length=50, verbose_name='标题')
    description = models.CharField(max_length=200, verbose_name='友情链接描述')
    callback_url = models.URLField(verbose_name='url地址')
    date_publish = models.DateTimeField(auto_now_add=True, verbose_name='发布时间')
    index = models.IntegerField(default=999, verbose_name='排列顺序(从小到大)')

    class Meta:
        verbose_name = '友情链接'
        verbose_name_plural = verbose_name
        ordering = ['index', 'id']

    def __unicode__(self):
        return self.title

# 广告
class Ad(models.Model):
    title = models.CharField(max_length=50, verbose_name='广告标题')
    description = models.CharField(max_length=200,  verbose_name='广告描述')
    image_url = models.ImageField(upload_to='ad/%Y/%m', verbose_name='图片路径')
    callback_url = models.URLField(null=True, blank=True, verbose_name='回调url')
    date_publish = models.DateTimeField(auto_now_add=True, verbose_name='发布时间')
    index = models.IntegerField(default=999, verbose_name='排列顺序(从小到大)')

    class Meta:
        verbose_name = u'广告'
        verbose_name_plural = verbose_name
        ordering = ['index', 'id']

    def __unicode__(self):
        return self.title

python_blog/blog/views.py
#coding:utf-8
from django.shortcuts import render
from django.conf import settings
from models import *
from django.core.paginator import Paginator, InvalidPage, EmptyPage, PageNotAnInteger
import  logging
# Create your views here.

logger = logging.getLogger('blog.views')

#设置全局setting，读取setting文件
def global_setting(request):

    return {'SITE_NAME':settings.SITE_NAME,
            'SITE_DESC':settings.SITE_DESC ,
            'WEIBO_SINA':settings.WEIBO_SINA,
            'WEIBO_TENCENT':settings.WEIBO_TENCENT,
            'PRO_RSS':settings.PRO_RSS,
            'PRO_EMAIL':settings.PRO_EMAIL}

def index(request):
    try:
        #分类信息获取(导航数据)
        category_list = Category.objects.all()
        #广告数据 TODO
        ad_list = Ad.objects.all()
        #标签云
        tag_list = Tag.objects.all()
        #最新文章数据
        article_list = Article.objects.all()
        paginator = Paginator(article_list,2)
        try:
            page = int(request.GET.get('page',1))
            article_list = paginator.page(page)
        except(EmptyPage,InvalidPage,PageNotAnInteger):
            article_list = paginator.page(1)
        #文章归档
        #获取文章中的 年-月
        print Article.objects.values("date_publish").distinct()
    except Exception as e:
        logger.error(e)
    return render(request, 'index.html',locals())

python_blog/templates/ad.html
{% load staticfiles %}
<div class="banner">
      <div id="slide-holder">
        <div id="slide-runner"> <a href="/" target="_blank"><img id="slide-img-1" src="{% static 'images/a1.jpg' %}"  alt="" /></a> <a href="/" target="_blank"><img id="slide-img-2" src="{% static 'images/a2.jpg' %}"  alt="" /></a> <a href="/" target="_blank"><img id="slide-img-3" src="{% static 'images/a3.jpg' %}"  alt="" /></a> <a href="/" target="_blank"><img id="slide-img-4" src="{% static 'images/a4.jpg' %}"  alt="" /></a>
          <div id="slide-controls">
            <p id="slide-client" class="text"><strong></strong><span></span></p>
            <p id="slide-desc" class="text"></p>
            <p id="slide-nav"></p>
          </div>
        </div>
      </div>
      <script>
    if(!window.slider) {
    var slider={};
  }

  slider.data= [
    {
        "id":"slide-img-1", // 与slide-runner中的img标签id对应
        "client":"标题1",
        "desc":"这里修改描述 这里修改描述 这里修改描述" //这里修改描述
    },
    {
        "id":"slide-img-2",
        "client":"标题2",
        "desc":"add your description here"
    },
    {
        "id":"slide-img-3",
        "client":"标题3",
        "desc":"add your description here"
    },
    {
        "id":"slide-img-4",
        "client":"标题4",
        "desc":"add your description here"
    }
  ];

    </script>
    </div>
    <!-- banner代码 结束 -->

python_blog/templates/archive.html
{% extends 'base.html' %}
{% load staticfiles %}
{% block left_content %}
    {% include 'ad.html' %}
    <div class="topnews">
      <h2>{{ request.GET.year }}/{{ request.GET.month }}文章归档</h2>
      {% for article in article_list %}
      <div class="blogs">
        <ul>
          <h3><a href="/">{{ article.title }}</a></h3>
          <p>{{ article.desc }}</p>
          <p class="autor"><span class="lm f_l">{% for tag in article.tag.all %}<a href="/">{{ tag.name }}</a>&nbsp;</span>{% endfor %}<span class="dtime f_l">{{ article.date_publish | date:'Y-m-d' }}</span><span class="viewnum f_r">浏览（<a href="/">{{ article.click_count }}</a>）</span><span class="pingl f_r">评论（<a href="/">{{ article.comment_set.all.count }}</a>）</span></p>
        </ul>
      </div>
      {% endfor %}
    </div>
    {% include 'pagination.html' %}
{% endblock %}

python_blog/templates/article.html
{% extends 'base.html' %}
{% load staticfiles %}
{% load myfilter %}
{% block left_content %}
    <div class="postdate">
      <div class="month">{{ article.date_publish | month_to_upper }}</div>
      <div class="date">{{ article.date_publish | date:'d' }}</div>
    </div>
    <div class="title">
        <h2><a href="" rel="bookmark" title="{{ article.title }}">{{ article.title }}</a></h2>
        <div class="postmeta">
          <span class="postmeta_author">{{ article.user.username }}</span>
          <span class="postmeta_category"><a href="" rel="category">{{ article.category.name }}</a></span>
          <span class="postmeta_time">{{ article.date_publish | date:'Y-m-d' }}</span>
        </div>
    </div>
        <div class="entry">
          {{ article.content | safe }}
        </div>
        <span class="tags">
            {% for tag in article.tag.all %}
            <a href="?tag={{ tag.name }}" rel="tag">{{ tag.name }}</a>
            {% endfor %}
        </span>
        <div class="info">
        Address:  <a href="{{ SITE_URL }}article/?id={{ article.id }}" rel="bookmark" title="{{ article.title }}">{{ SITE_URL }}article/?id={{ article.id }}</a>
        </div>

      <div class="commentstitle"><h3 id="comments"><span class="commentsnumber">only 1 comment</span> untill now</h3></div>

      <ol class="commentlist">
          {% for comment in comment_list %}
          <li id="comment-59418">
                <div class="top"><a href='{{ comment.url }}' rel='external nofollow' class='url'>{{ comment.username }}</a><span class="time"> @ <a href="#comment-59418" title="">{{ comment.date_publish | date:'Y-m-d H:i:s' }}</a></span></div>
                <div><img alt='' src='{% static 'images/default.jpg' %}' class='avatar avatar-32 photo' height='32' width='32' /></div>

                <div class="body">
                                <p>{{ comment.content }}</p>
                </div>
          </li>
          {% for children_comment in comment.children_comment %}
          <li id="comment-59542">
                <div class="reply">
                  <div class="top"><a href="{{ children_comment.url }}" rel="external nofollow" class="url">{{ children_comment.username }}</a><span class="time"> @ <a href="#comment-59543" title="">{{ children_comment.date_publish | date:'Y-m-d H:i:s' }}</a></span></div>
                  <div><img alt="" src="{% static 'images/default.jpg' %}" class="avatar avatar-32 photo" height="32" width="32"></div>

                  <div class="body">
                                        {{ children_comment.content }}                  </div>
                </div>
          </li>
          {% endfor %}
          {% endfor %}
      </ol>

    <div id="commentform">
    <h3 id="respond">Add your comment now</h3>
    {% if not request.user.is_authenticated %}
    <div class='login_info'>还没有登陆？可以登录后再评论哦。<b><a href="{% url 'login' %}">&raquo;去登录</a>&nbsp;<a href="{% url 'reg' %}">&raquo;去注册</a></b></div>
    {% else %}
    <div class='login_info'><b>{{ request.user.username }}</b>,快来写点评论吧!&nbsp;<a href="{% url 'logout' %}">注销</a></div>
    {% endif %}
    <form action="{% url 'comment_post' %}" method="post">
    {% csrf_token %}
    <p>{{ comment_form.author }}
    <label for="author">Name (required)</label></p>

    <p>{{ comment_form.email }}
    <label for="email">Email (Will NOT be published) (required)</label></p>

    <p>{{ comment_form.url }}
    <label for="url">URL</label></p>


    <!--<p><small><strong>XHTML:</strong> You can use these tags: &lt;a href=&quot;&quot; title=&quot;&quot;&gt; &lt;abbr title=&quot;&quot;&gt; &lt;acronym title=&quot;&quot;&gt; &lt;b&gt; &lt;blockquote cite=&quot;&quot;&gt; &lt;cite&gt; &lt;code class=&quot;&quot; title=&quot;&quot; data-url=&quot;&quot;&gt; &lt;del datetime=&quot;&quot;&gt; &lt;em&gt; &lt;i&gt; &lt;q cite=&quot;&quot;&gt; &lt;strike&gt; &lt;strong&gt; &lt;pre class=&quot;&quot; title=&quot;&quot; data-url=&quot;&quot;&gt; &lt;span class=&quot;&quot; title=&quot;&quot; data-url=&quot;&quot;&gt; </small></p>-->

    <p>{{ comment_form.comment }}</p>

    <p>
        {{ comment_form.article }}
        <input name="submit" type="submit" id="submit" tabindex="5" value="Submit" class="button" />
    </p>
    </form>
    </div>
{% endblock %}

python_blog/templates/base.html
{% load staticfiles %}
<!doctype html>
<html>
<head>
<meta charset="utf-8">
<title>{{ SITE_NAME }}</title>
<meta name="keywords" content="{{ SITE_NAME }}" />
<meta name="description" content="{{ SITE_DESC }}" />
<link href="{% static 'css/base.css' %}" rel="stylesheet">
<link href="{% static 'css/index.css' %}" rel="stylesheet">
{% block custom_css %}{% endblock %}
<script type="text/javascript" src="{% static 'js/jquery.min.js' %}"></script>
<script type="text/javascript" src="{% static 'js/sliders.js' %}"></script>
<!--[if lt IE 9]>
<script src="js/modernizr.js"></script>
<![endif]-->
{% block custom_js %}{% endblock %}
</head>
<body>
<header>
  <div class="logo">
      <h1>{{ SITE_NAME }}</h1>
      <p>{{ SITE_DESC }}</p>
  </div>
  <nav id="topnav" class="f_r">
    <ul>
      {% for category in category_list %}
      <a href="base.html" target="_blank">{{ category.name }}</a>
      {% endfor %}
    </ul>
    <script src="{% static 'js/nav.js' %}"></script>
  </nav>
</header>
<article>
  <div class="l_box f_l">
      {% block left_content %}{% endblock %}
  </div>
  <div class="r_box f_r">
    <div class="tit01">
      <h3>关注我</h3>
      <div class="gzwm">
        <ul>
          <li><a class="xlwb" href="#" target="_blank">新浪微博</a></li>
          <li><a class="txwb" href="#" target="_blank">腾讯微博</a></li>
          <li><a class="rss" href="portal.php?mod=rss" target="_blank">RSS</a></li>
          <li><a class="wx" href="mailto:admin@admin.com">邮箱</a></li>
        </ul>
      </div>
    </div>
    <!--tit01 end-->
    <div class="moreSelect" id="lp_right_select">
      <script>
window.onload = function ()
{
  var oLi = document.getElementById("tab").getElementsByTagName("li");
  var oUl = document.getElementById("ms-main").getElementsByTagName("div");

  for(var i = 0; i < oLi.length; i++)
  {
    oLi[i].index = i;
    oLi[i].onmouseover = function ()
    {
      for(var n = 0; n < oLi.length; n++) oLi[n].className="";
      this.className = "cur";
      for(var n = 0; n < oUl.length; n++) oUl[n].style.display = "none";
      oUl[this.index].style.display = "block"
    }
  }
}
</script>
      <div class="ms-top">
        <ul class="hd" id="tab">
          <li class="cur"><a href="/">浏览排行</a></li>
          <li><a href="/">评论排行</a></li>
          <li><a href="/">站长推荐</a></li>
        </ul>
      </div>
      <div class="ms-main" id="ms-main">
        <div style="display: block;" class="bd bd-news" >
          <ul>
            <li><a href="/" target="_blank">住在手机里的朋友</a></li>
            <li><a href="/" target="_blank">教你怎样用欠费手机拨打电话</a></li>
            <li><a href="/" target="_blank">原来以为，一个人的勇敢是，删掉他的手机号码...</a></li>
            <li><a href="/" target="_blank">手机的16个惊人小秘密，据说99.999%的人都不知</a></li>
            <li><a href="/" target="_blank">你面对的是生活而不是手机</a></li>
            <li><a href="/" target="_blank">豪雅手机正式发布! 在法国全手工打造的奢侈品</a></li>
          </ul>
        </div>
        <div  class="bd bd-news">
          <ul>
            {% for article in article_comment_list %}
            <li><a href="/" target="_blank">{{ article.title | slice:':15' }}</a></li>
            {% endfor %}
          </ul>
        </div>
        <div class="bd bd-news">
          <ul>
            <li><a href="/" target="_blank">手机的16个惊人小秘密，据说99.999%的人都不知</a></li>
            <li><a href="/" target="_blank">你面对的是生活而不是手机</a></li>
            <li><a href="/" target="_blank">住在手机里的朋友</a></li>
            <li><a href="/" target="_blank">豪雅手机正式发布! 在法国全手工打造的奢侈品</a></li>
            <li><a href="/" target="_blank">教你怎样用欠费手机拨打电话</a></li>
            <li><a href="/" target="_blank">原来以为，一个人的勇敢是，删掉他的手机号码...</a></li>
          </ul>
        </div>
      </div>
      <!--ms-main end -->
    </div>
    <!--切换卡 moreSelect end -->

    <div class="cloud">
      <h3>标签云</h3>
      <ul>
          {% for tag in tag_list %}
            <li><a href="/">{{ tag.name }}</a></li>
          {% endfor %}
      </ul>
    </div>
    <div class="tuwen">
      <h3>文章归档</h3>
      <ul>
        {% for archive in archive_list %}
        <li>
          <p><span class="tutime font-size-18"><a href='{% url 'archive' %}?year={{ archive | slice:":4" }}&month={{ archive | slice:"5:7" }}'>{{ archive }}</a></span></p>
        </li>
        {% endfor %}
      </ul>
    </div>
    <div class="links">
      <h3>友情链接</h3>
      <ul>
        <li><a href="/">web开发</a></li>
        <li><a href="/">前端设计</a></li>
        <li><a href="/">Html</a></li>
        <li><a href="/">CSS3</a></li>
        <li><a href="/">Html5+css3</a></li>
        <li><a href="/">百度</a></li>
      </ul>
    </div>
  </div>
  <!--r_box end -->
</article>
<footer>
  <p class="ft-copyright">{{ SITE_NAME }} 蜀ICP备xxxxxxx号-1</p>
  <div id="tbox"> <a id="togbook" href="/"></a> <a id="gotop" href="javascript:void(0)"></a> </div>
</footer>
</body>
</html>

python_blog/templates/category.html
{% extends 'base.html' %}
{% load staticfiles %}
{% block left_content %}
    {% include 'ad.html' %}
    <div class="topnews">
      <h2>{{ category.name }}</h2>
      {% for article in article_list %}
      <div class="blogs">
        <ul>
          <h3><a href="/">{{ article.title }}</a></h3>
          <p>{{ article.desc }}</p>
          <p class="autor"><span class="lm f_l">{% for tag in article.tag.all %}<a href="/">{{ tag.name }}</a>&nbsp;</span>{% endfor %}<span class="dtime f_l">{{ article.date_publish | date:'Y-m-d' }}</span><span class="viewnum f_r">浏览（<a href="/">{{ article.click_count }}</a>）</span><span class="pingl f_r">评论（<a href="/">{{ article.comment_set.all.count }}</a>）</span></p>
        </ul>
      </div>
      {% endfor %}
    </div>
    {% include 'pagination.html' %}
{% endblock %}

python_blog/templates/failure.html
<!DOCTYPE html>
<html lang="zh-cn">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="renderer" content="webkit">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">
    <title>操作失败</title>
    <link href="http://www.maiziedu.com/static/css/base.css" rel="stylesheet">
    <link href="http://www.maiziedu.com/static/css/microoh-v5.css" rel="stylesheet">
    <style type="text/css">
        ul li{float: left; margin-left: 10px;}
    </style>
</head>

<body>
<div class="microoh-main" style="height: 150px">
    <div class="container" style="position: absolute; top: 20px; left: 20px;">
        <div style="height: 150px">
            <i class="v5-icon v5-icon-wrong"></i>
            <span>{{ reason | safe }}</span>
        </div>
    </div>
</div>
</body>
</html>

python_blog/templates/index.html
{% extends 'base.html' %}
{% load staticfiles %}
{% block left_content %}
    {% include 'ad.html' %}
    <div class="topnews">
      <h2>最新文章</h2>
        {% for article in article_list%}
      <div class="blogs">
        <ul>
          <h3><a href="/">{{ article.title }}</a></h3>
          <p>{{ article.desc }}</p>
          <p class="autor"><span class="lm f_l">{% for tag in article.tag.all %}<a href="/">{{ tag.name }}</a>{% endfor %}</span><span class="dtime f_l">{{ article.date_publish | date:'Y-m-d' }}</span><span class="viewnum f_r">浏览（<a href="/">{{ article.click_count }}</a>）</span><span class="pingl f_r">评论（<a href="/">{{ article.comment_set.all.count }}</a>）</span></p>
        </ul>
      </div>
        {% endfor %}
    </div>
    {% include 'pagination.html' %}
  </div>
  </div>
{% endblock %}

python_blog/templates/login.html
{% load staticfiles %}
<!DOCTYPE html>
<html>
<head>
		<meta charset="utf-8">
		<link href="{% static 'css/reglogin.css' %}" rel='stylesheet' type='text/css' />
		<meta name="viewport" content="width=device-width, initial-scale=1">
</head>
<body>
	<div class="main">
		<div class="header" >
			<h1>Login!</h1>
		</div>
		<p></p>
			<form action="{% url 'login' %}" method="post">
                {% csrf_token %}
				<ul class="right-form">
					<h2>Login:</h2>
					<li><input type="text" name="username" placeholder="Username" required/></li>
					<li><input type="password" name="password" placeholder="Password" required/></li>
					<input type="hidden" name="source_url" value="{{ request.META.HTTP_REFERER }}">
                    <input type="submit" value="Login" >
					<div class="clear"> </div>
				</ul>
				<div class="clear"> </div>

			</form>
	</div>
</body>
</html>

python_blog/templates/pagination.html
<div id="pagination">
    <ul id="pagination-flickr">
    {% if article_list.has_previous %}
    <li class="previous"><a href="?page={{ article_list.previous_page_number }}{% if request.GET.year %}&year={{ request.GET.year }}{% endif %}{% if request.GET.month %}&month={{ request.GET.month }}{% endif %}{% if request.GET.cid %}&cid={{ request.GET.cid }}{% endif %}">&laquo;上一页</a></li>
    {% else %}
    <li class="previous-off">&laquo;上一页</li>
    {% endif %}
     <li class="active">{{ article_list.number }}/{{ article_list.paginator.num_pages }}</li>
    {% if article_list.has_next %}
      <li class="next"><a href="?page={{ article_list.next_page_number }}{% if request.GET.year %}&year={{ request.GET.year }}{% endif %}{% if request.GET.month %}&month={{ request.GET.month }}{% endif %}{% if request.GET.cid %}&cid={{ request.GET.cid }}{% endif %}">下一页 &raquo;</a></li>
    {% else %}
      <li class="next-off">下一页 &raquo;</li>
    {% endif %}
   </ul>
</div>

python_blog/templates/reg.html
{% load staticfiles %}
<!DOCTYPE html>
<html>
<head>
		<meta charset="utf-8">
		<link href="{% static 'css/reglogin.css' %}" rel='stylesheet' type='text/css' />
		<meta name="viewport" content="width=device-width, initial-scale=1">
</head>
<body>
	<div class="main">
		<div class="header" >
			<h1>Create a Free Account!</h1>
		</div>
		<p></p>
			<form action="{% url 'reg' %}" method="post">
                {% csrf_token %}
				<ul class="left-form">
					<h2>New Account:</h2>
					<li>
						{{ reg_form.username }}
						<div class="clear"> </div>
					</li> 
					<li>
						{{ reg_form.email }}
						<div class="clear"> </div>
					</li> 
					<li>
						{{ reg_form.url }}
						<div class="clear"> </div>
					</li> 
					<li>
                        {{ reg_form.password }}
						<div class="clear"> </div>
					</li>
                    <input type="hidden" name="source_url" value="{{ request.META.HTTP_REFERER }}">
					<input type="submit" value="Create And Login">
					<div class="clear"> </div>
				</ul>
				<div class="clear"> </div>
			</form>
	</div>
</body>
</html>

python_blog/templates/success.html
<!DOCTYPE html>
<html lang="zh-cn">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="renderer" content="webkit">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">
    <title>操作成功</title>
    <link href="http://www.maiziedu.com/static/css/base.css" rel="stylesheet">
    <link href="http://www.maiziedu.com/static/css/microoh-v5.css" rel="stylesheet">
</head>

<body>
<div class="microoh-main" style="height: 100px">
    <div style="position: absolute; top: 20px; left: 20px;">
            <i class="v5-icon v5-icon-right"></i>
            <span>{{ reason | safe }}</span>
    </div>
</div>
</body>
</html>